subarch: amd64
target: stage1
version_stamp: musl-clang-latest
rel_type: musl-clang
profile: default/linux/amd64/17.0/musl/clang
snapshot_treeish: latest
source_subpath: musl/clang/stage3-amd64-musl-clang
compression_mode: gzip
update_seed: no
