subarch: amd64
target: stage3
version_stamp: musl-clang-latest
rel_type: musl-clang
profile: default/linux/amd64/17.0/musl/clang
snapshot_treeish: latest
source_subpath: musl/musl-clang/stage2-amd64-musl-clang-latest.tar.gz
compression_mode: gzip
#portage_confdir: @REPO_DIR@/releases/portage/stages
#portage_prefix: releng
