#!/bin/bash

export ADDR2LINE="llvm-addr2line"
export AR="llvm-ar"
export AS="llvm-as"
export CC="clang"
export CXX="clang++"
export LD="ld.lld"
export NM="llvm-nm"
export OBJCOPY="llvm-objcopy"
export OBJDUMP="llvm-objdump"
export RANLIB="llvm-ranlib"
export READELF="llvm-readelf"
export STRINGS="llvm-strings"
export STRIP="llvm-strip"

export CFLAGS="-fPIC -fstack-protector-strong -D_FORTIFY_SOURCE=2 -O3 -march=native -pipe -flto=thin"
export CXXFLAGS="${CFLAGS}"

CATALYST_USE="${CATALYST_USE} -X"
CATALYST_USE="${CATALYST_USE} -accessibility"
CATALYST_USE="${CATALYST_USE} -bash-completion"
CATALYST_USE="${CATALYST_USE} -bluetooth"
CATALYST_USE="${CATALYST_USE} -branding"
CATALYST_USE="${CATALYST_USE} -doc"
CATALYST_USE="${CATALYST_USE} -examples"
CATALYST_USE="${CATALYST_USE} -man"
CATALYST_USE="${CATALYST_USE} -ncurses"
CATALYST_USE="${CATALYST_USE} -sqlite"
CATALYST_USE="${CATALYST_USE} -systemd"
CATALYST_USE="${CATALYST_USE} -test"

export CATALYST_USE
