subarch: amd64
target: stage1
version_stamp: musl-clang-lto
rel_type: musl-clang-lto
profile: default/linux/amd64/17.0/musl/clang
snapshot_treeish: latest
source_subpath: musl/clang/stage3-amd64-musl-clang.tar
compression_mode: gzip
update_seed: no
repos: /run/stage3/var/db/repos/gentoo
#portage_confdir: /run/stage3/etc/portage
